### ISSUE TITLE
Error encountered Quickstart step 4 - Launch the Docker container using the run_dev.sh script

### ISSUE THREAD

**Issue by jimbog13** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#12]
jimbog13@Haluin:~/workspaces/isaac_ros-dev/src/isaac_ros_common$ cd ~/workspaces/isaac_ros-dev/src/isaac_ros_common &&   ./scripts/run_dev.sh
isaac_ros_dev not specified, assuming /home/jimbog13/workspaces/isaac_ros-dev
Building x86_64.ros2_humble.user base as image: isaac_ros_dev-x86_64 using key x86_64.ros2_humble.user
Using base image name not specified, using ''
Using docker context dir not specified, using Dockerfile directory
Resolved the following Dockerfiles for target image: x86_64.ros2_humble.user
/home/jimbog13/workspaces/isaac_ros-dev/src/isaac_ros_common/scripts/../docker/Dockerfile.user
/home/jimbog13/workspaces/isaac_ros-dev/src/isaac_ros_common/scripts/../docker/Dockerfile.x86_64.ros2_humble
Building /home/jimbog13/workspaces/isaac_ros-dev/src/isaac_ros_common/scripts/../docker/Dockerfile.x86_64.ros2_humble as image: x86_64-ros2_humble-image with base:
[+] Building 798.7s (4/4) FINISHED
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile.x86_64.ros2_humble                                            0.0s
 => => transferring dockerfile: 567B                                                                               0.0s
 => [internal] load metadata for nvcr.io/nvidia/isaac/ros:x86_64-ros2_humble_1930bbec7e7704243656b695b9df7844      1.9s
 => ERROR [1/1] FROM nvcr.io/nvidia/isaac/ros:x86_64-ros2_humble_1930bbec7e7704243656b695b9df7844@sha256:a8aac6  796.7s
 => => resolve nvcr.io/nvidia/isaac/ros:x86_64-ros2_humble_1930bbec7e7704243656b695b9df7844@sha256:a8aac60bbf643d  0.0s
 => => sha256:6ee22543019361b997cf945faa83f79c851bfc2ee11fb73b00a768281bf50062 110.85MB / 110.85MB                97.7s
 => => sha256:a8aac60bbf643da4357eaa362b4cfd83b2dcbff3409bfc6c99642324e2dabaf5 11.88kB / 11.88kB                   0.0s
 => => sha256:d3a4d8f6a367b70a8cb87b4d882d5b6dc6671cba5d983db299cb477c2e1db4db 41.92kB / 41.92kB                   0.0s
 => => sha256:675920708c8bf10fbd02693dc8f43ee7dbe0a99cdfd55e06e6f1a8b43fd08e3f 28.57MB / 28.57MB                  30.3s
 => => sha256:8b1a583c6b123c1d24c6d18814f906479fa97d40aa479ea9c57ffafd769dfa00 133.38MB / 133.38MB               118.1s
 => => extracting sha256:675920708c8bf10fbd02693dc8f43ee7dbe0a99cdfd55e06e6f1a8b43fd08e3f                          0.5s
 => => sha256:7302be10edc2df7474a3d96a4b156ca72481cd81839c09c6f4358647bb8aa905 182.12kB / 182.12kB                30.8s
 => => sha256:5bf9d046b7e1b061d707a4449bf57e4eb105a0b13ccf4f61dd8cb28c0b13a7fe 1.01GB / 2.76GB                   796.7s
 => => extracting sha256:6ee22543019361b997cf945faa83f79c851bfc2ee11fb73b00a768281bf50062                          1.7s
 => => sha256:b4f5e997e3c2dad9cf9ad02270cd77ce0e10bc946d87c8dd675440ca0030c227 11.55kB / 11.55kB                  98.0s
 => => sha256:d0e445bfbc9d40c3fe0e3f218f1b9178aebcc88315d069a1a4a90c1e4f6b41c7 186B / 186B                        98.2s
 => => sha256:a86d67d9ff4b97b30eaa4f687485e9751b05fdd66b169abf6b1b045fdb009a80 5.11kB / 5.11kB                    98.5s
 => => sha256:51d596db94d9bdaa8d36cd57b1653835bb93a657df3e636e0f1d4c6a9fa0274b 139.30kB / 139.30kB                99.0s
 => => sha256:a8bdaac63bdf31fe5c545c6b07590b9e214a4d3ae85e5029af86cdac3788c8b9 40.76MB / 40.76MB                 140.0s
 => => sha256:299ca652228e4a3020aeee30c4c156f4f262fac5309039d38c6c8202b9cb69da 94.98MB / 94.98MB                 213.2s
 => => extracting sha256:8b1a583c6b123c1d24c6d18814f906479fa97d40aa479ea9c57ffafd769dfa00                          1.7s
 => => extracting sha256:7302be10edc2df7474a3d96a4b156ca72481cd81839c09c6f4358647bb8aa905                          0.0s
 => => sha256:2d72ec5f9761ea24dae10afa57c8ebcbc2a5a8282cfa7ff42992ac9748bff541 508B / 508B                       140.1s
 => => sha256:36eb1c09fe219361eb42ba6fa908acb54ce4cd54f79a5f80b809781d98dd4cf9 458.39MB / 458.39MB               542.7s
 => => sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B                         213.5s
 => => sha256:86c00dc0adeab74cc18c9170d862ff7856b757fcc7b4d8c9ce15c166b382d30c 1.85kB / 1.85kB                   213.7s
 => => sha256:ce54f801f45dd44cf28f8a2c50cdb5663f27318b2c679773c5e4283fa79fe63e 33.81MB / 33.81MB                 238.5s
 => => sha256:2a2d214e96d9418e62f01d1dabb9ebf7613862dbe65f92cd85f7d9381a8868ac 224.22MB / 224.22MB               433.5s
 => => sha256:0686f1ac9123e0642e045a6cd40e1b970e0e113da4331df5e64c24f109a6e599 11.85kB / 11.85kB                 434.3s
 => => sha256:5c78e5ffd4774e4652bfbe44b20f9ff34a33c1c623d7b6dc368a70293c63e025 57.33MB / 57.33MB                 484.3s
 => => sha256:289e40b0cf4e6d81ef5b4ae57fa38fa4e72b883b78fef84fb11505a79fce81ae 154B / 154B                       484.5s
 => => sha256:2d778e767a354f0ce3abc0498e4c8efc8abee67ee774666bb9ae98fa39867bed 757B / 757B                       484.6s
 => => sha256:3e74972b8f3b4f2de9cc1a398ec01e6f3e3b088443eb6fb9e3e514db4450d843 436.21MB / 2.63GB                 796.7s
 => => sha256:2da5ef9592ad14727d95496845d4da5016b8ba6e5ced02361fe168611f6a6df4 2.80MB / 2.80MB                   545.8s
 => => sha256:8496c7c2610587c1a62253361ecf3da14d0fd5e4c01709af04fcc56d9f698042 1.99kB / 1.99kB                   546.0s
 => => sha256:43e5b3d88ccc700604419ab18d66225aa8712845956a7a0dfe01199352368f6d 185.68kB / 185.68kB               546.4s
 => => sha256:10632fc3e099171b467ebd9aea41043059c492f9374a8172882337a406852f40 85.93MB / 85.93MB                 630.7s
 => => sha256:d054aebd23960628db7844c94e8ea58fd00fe318d200af5702e47199b121a808 2.61kB / 2.61kB                   630.9s
 => => sha256:bd7ff8a90f190b1d3b4b01083e3857ea221575b4bccf406961e8bc0b02a347f5 17.53MB / 17.53MB                 648.4s
 => => sha256:e4dc74ae1c04f107740bc37027fd3245b201f31a507f847221d0d0f7f80daf4a 81.63MB / 81.63MB                 720.1s
 => => sha256:3a755839b638f3b4e50b1a706d7c27ee226dde4c0283f5c3564cd0803288e94c 0B / 277.78MB                     796.7s
------
 > [1/1] FROM nvcr.io/nvidia/isaac/ros:x86_64-ros2_humble_1930bbec7e7704243656b695b9df7844@sha256:a8aac60bbf643da4357eaa362b4cfd83b2dcbff3409bfc6c99642324e2dabaf5:
------
Dockerfile.x86_64.ros2_humble:9
--------------------
   7 |     # license agreement from NVIDIA CORPORATION is strictly prohibited.
   8 |
   9 | >>> FROM nvcr.io/nvidia/isaac/ros:x86_64-ros2_humble_1930bbec7e7704243656b695b9df7844
  10 |
--------------------
ERROR: failed to solve: failed to fetch anonymous token: unexpected status: 401 Unauthorized
Failed to build base image: isaac_ros_dev-x86_64, aborting.

**Comment by ashwinvkNV** [comment]
This issue is specific to the isaac_ros_common docker container. Can you please open and issue here: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/issues
