### ISSUE TITLE
Reference Implementation

### ISSUE THREAD

**Issue by grassjelly** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#13]
Hi,

Thanks for releasing this package. Just wondering if there's any published paper where this implementation has been based on?

**Comment by ashwinvkNV** [comment]
No the underlying global localization algorithm is currently proprietary and provided as binary [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros/blob/main/isaac_ros_gxf/gxf/ext/lib/gxf_x86_64_cuda_11_8/libgxf_flatscan_localization.so).
