### ISSUE TITLE
trigger_grid_search_localization service call publishes nothing to /localization_result, with gxf/std/double_buffer_receiver.cpp warning. 

### ISSUE THREAD

**Issue by milesprieb** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#15]
I am getting the following warning from isaac_ros_occupancy_grid_localizer_quickstart.launch.py, with nothing published to /localization_result: 

> [component_container_mt-1] 2023-07-24 11:09:49.574 WARN  gxf/std/double_buffer_receiver.cpp@78: Push failed on 'rx_flatscan'

**Comment by swapnesh-wani-nvidia** [comment]
Could you please add the full log to diagnose this issue? Also, steps to reproduce it. Thanks.
