### ISSUE TITLE
PointCloud2 to FlatScan contains no Data

### ISSUE THREAD

**Issue by Floskinner** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#16]
## What I do
Start the pointcloud to flatscan launch file:
```bash
ros2 launch isaac_ros_pointcloud_utils isaac_ros_pointcloud_to_flatscan.launch.py
```
Start the FlatScan to LaserScan (to see the result in rviz)
```bash
ros2 launch isaac_ros_pointcloud_utils isaac_ros_flatscan_to_laserscan.launch.py
```
Start publishing my ros2 bag with the sensor_msgs/msg/PointCloud2 messages:
```bash
ros2 bag play my_rosbag
```

## What I expect
The PointCloud2 messages are converted into FlatScan and into LaserScan.

## The Problem
The FlatScan / LaserScan contain no Data:

<details><summary>FlatScan</summary>
<p>

header:
  stamp:
    sec: 1693559265
    nanosec: 6811791
  frame_id: camera_3d_optical_link
range_min: 0.0
range_max: 0.0
angles:
- 0.0
- 0.0
...ONLY MORE 0.0...
intensities: []

</p>
</details> 

## My enviorment
The PointCloud2 Data is valid. I can show them in rviz and if I "echo" them I got data in it. The topic is `/pointcloud`
<details><summary>PointCloud</summary>
<p>

![image](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/assets/58706771/946ccd4d-30e4-4f15-9711-12d3c2d7a81e)

header:
  stamp:
    sec: 1693559265
    nanosec: 6811791
  frame_id: camera_3d_optical_link
height: 172
width: 224
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
is_bigendian: false
point_step: 12
row_step: 2688
data:
CUT SOME 0 VALUES
- 63
- 225
- 233
- 52
- 63
- 34
- 167
- 214
- 190
- 224
- 221
- 80
- 63
- 167
- 102
- 54
- 63
- 208
- 247
- 213
- 190
- 152
- 251
- 78
- 63
- 134
- 113
- 59
- 63
- 233
- 130
- 217
- 190
- 92
- 28
- 81
- 63
CUT SOME MORE VALUES

</p>
</details>

I use the `master` Branche and the docker container. I already used only LaserScan for the pose estimation with the same setup (it worked). So I guess the container is setup correct.

My Hardware is a Jetson Orin Nano Developer Kit.

**Comment by jaiveersinghNV** [comment]
Could you please try this again on our [latest release](https://nvidia-isaac-ros.github.io/releases/index#isaac-ros-2-0-0-october-18-2023)?

If you're still experiencing this issue, please upload a rosbag with your sample data, and we'll try to replicate this problem on our end.
