### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by sandeepdutta** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#18]
I had to add
find_package(isaac_ros_nitros REQUIRED)
to
isaac_ros_occupancy_grid_localizer/CMakeLists.txt
isaac_ros_pointcloud_utils/CMakeLists.txt
for it to build without erros.
Sandeep

**Comment by swapnesh-wani-nvidia** [comment]
Could you please post the full logs as well as the steps to reproduce the issue?

`ament_auto_find_build_dependencies()` is there in both the CMakelists: [isaac_ros_occupancy_grid_localizer/CMakeLists.txt](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/blob/main/isaac_ros_occupancy_grid_localizer/CMakeLists.txt#L26) and [isaac_ros_pointcloud_utils/CMakeLists.txt](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/blob/main/isaac_ros_pointcloud_utils/CMakeLists.txt#L26) which will pull out the required dependencies from the respective `package.xml`
