### ISSUE TITLE
LIDAR FOV Problems IsaacSIM and Carter robot

### ISSUE THREAD

**Issue by pabloinigoblasco** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#25]
The default Carter robot in Isaac 2023 has a 3D lidar with a very small FOV, causing problems for SLAM and isaac_ros_grid_localization funcioning (more in problem 4).
- Adjustments to Lidar Scanner Angle: 2023 version scans below 60°, previously in 2022 was 100°; ideal lidar reading would be 260°-360°. 
   - **Request:** Need to configure the LIDAR in Isaac Sim to increase the FOV for effective operation. Instructions to change the settings of the FOV in IsaacSIM.
   - **Fix attempt:** We decreased the isaac_ros_occupancy_grid_localizer FOV parameter ([ref](https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_map_localization/isaac_ros_occupancy_grid_localizer/index.html)) min_scan_fov_degrees to 60º, but with that configuration value the isaac_ros_occupancy_grid_localizer is unable to work consistently localizing the robot, even unable to make the radial pattern.
 
The isaac_ros_occupancy_grid_localizer struggles to function properly in IsaacSim 2023 due to the limited FOV of the lidar. The default configuration of the localizer isn't equipped to handle such a small FOV (under 60º).

Isaac_occupancy_grid_localizer operates with limited precision, a noticeable contrast to its more effective performance in the IsaacSim 2022 demo, which benefitted from a larger FOV.

![image](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/assets/13334595/56e4e291-8a9b-49a4-b758-a107f7342538)

**Comment by brettpac** [comment]
This can also be seen in the first video on this page...
[https://docs.omniverse.nvidia.com/isaacsim/latest/landing_pages/carter_nova_landing_page.html](https://docs.omniverse.nvidia.com/isaacsim/latest/landing_pages/carter_nova_landing_page.html)

When you look at the generated pointcloud, one can see clearly that it's is dealing with a ~60 degree FOV.

**Comment by jaiveersinghNV** [comment]
Hi @pabloinigoblasco @brettpac ,

[Isaac Sim 2023.1.1](https://docs.omniverse.nvidia.com/isaacsim/latest/release_notes.html#id1) has just been released, and it should have a fix for this LIDAR bug. Could you please update to the latest Isaac Sim version and try again?

**Comment by brettpac** [comment]
Hi @jaiveersinghNV, after a series of discussions with Ashwin & Gordon, the decision was made to not use the map_localizer package in the application and instead just use amcl.

So, I think this issue is safe to close. 
Thank you,
