### ISSUE TITLE
Lack of Precision in Isaac ROS Ocupancy Grid Localizer

### ISSUE THREAD

**Issue by pabloinigoblasco** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#26]
**Issue Description**: Insufficient precision in isaac_ros_occupancy_grid_localizer for the Carter robot, leading to inconsistent pose estimation between consecutive time steps.
**Consequence:** Results in a visually jarring "jump effect" in position estimation during radial motion execution in RViz.
**Impressions:**  isaac_ros_occupancy_grid_localizer might be misconfigured for the current robot/lidar setup. The new FOV in the 2023 version is suspected to be a contributing factor, as the localization worked in 2022 but is problematic in 2023. 
**Evidence:** 

VIDEO: https://www.dropbox.com/scl/fi/hqhltqwemr0nujmjuznc5/2023-11-06-10-30-55_sm_isaac_exp_grid_loc_problem.mp4?rlkey=ilv0qvvz1n59jpab95rn6ck7s&dl=0

![image](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/assets/13334595/89827de9-f844-4a6f-982d-2127079a7188)

**Comment by gordongrigor** [comment]
isaac_ros_occupancy_grid_localizer is designed to provide an initial global localization.  It's not a continuous localization package.

**Comment by tugbakara** [comment]
In the documentation page of this package [there is a note ](https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_map_localization/isaac_ros_occupancy_grid_localizer/index.html#:~:text=Or%20publish%20directly%20to%20the%20flatscan_localization%20topic%20to%20trigger%20localization%20every%20time%20a%20FlatScan%20message%20is%20received%20on%20this%20topic.)about the continuous localization. Am I wrong or what do you mean for this note? I am confused.

**Comment by HappySamuel** [comment]
> In the documentation page of this package [there is a note ](https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_map_localization/isaac_ros_occupancy_grid_localizer/index.html#:~:text=Or%20publish%20directly%20to%20the%20flatscan_localization%20topic%20to%20trigger%20localization%20every%20time%20a%20FlatScan%20message%20is%20received%20on%20this%20topic.)about the continuous localization. Am I wrong or what do you mean for this note? I am confused.

Agree with @tugbakara , I thought that `/flatscan_localization` is used for continuous localization as well.  As it's written that whenever flatscan is sent to here, localization will be triggered.
